feat: service alunos
JuannCarloss/ged-app pull request #4
Opened 2024-11-09 00:01 UTC by Mateusvp1

2024-11-09 02:27 UTC, lucas0headshot requested changes
Duas coisinhas...

2024-11-09 02:27 UTC, lucas0headshot commented on src/main/java/br/apae/ged/service/AlunoService.java
> +package br.apae.ged.service;
Alterar para o pacote "services"

2024-11-09 02:27 UTC, lucas0headshot commented on src/main/java/br/apae/ged/exception/AlunoNaoEncontradoException.java
> +package br.apae.ged.exception;
Alterar para o pacote "exceptions"

2024-11-15 01:34 UTC, JuannCarloss approved these changes

2024-11-15 01:34 UTC, merged